"use client"

import type React from "react"
import { createContext, useContext, useState, useEffect } from "react"

type Language = "ru" | "en"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}

interface LanguageProviderProps {
  children: React.ReactNode
}

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [language, setLanguage] = useState<Language>("ru")

  useEffect(() => {
    const savedLanguage = localStorage.getItem("language") as Language
    if (savedLanguage && (savedLanguage === "ru" || savedLanguage === "en")) {
      setLanguage(savedLanguage)
    }
  }, [])

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang)
    localStorage.setItem("language", lang)
  }

  const t = (key: string): string => {
    return translations[language][key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

const translations = {
  ru: {
    // Auth
    "auth.aiCoach": "AI Коуч",
    "auth.personalCompanion": "Ваш персональный помощник в развитии",
    "auth.password": "Пароль",
    "auth.login": "Войти",
    "auth.register": "Зарегистрироваться",
    "auth.noAccount": "Нет аккаунта?",
    "auth.alreadyAccount": "Уже есть аккаунт?",
    "auth.registrationError": "Ошибка регистрации",
    "auth.registrationFailedGeneric": "Не удалось зарегистрироваться. Пожалуйста, попробуйте еще раз.",
    "auth.registrationSuccess": "Регистрация успешна",
    "auth.checkEmailForConfirmation": "Пожалуйста, проверьте свою почту для подтверждения.",
    "auth.accessDenied": "Доступ запрещен",
    "auth.linkExpired": "Срок действия ссылки истек или она недействительна.",
    "auth.contactTelegram": "Связаться с поддержкой в Telegram",

    // Onboarding
    "onboarding.step": "Шаг",
    "onboarding.of": "из",
    "onboarding.personalizeExperience": "Давайте персонализируем ваш опыт коучинга",
    "onboarding.whatsYourName": "Как вас зовут?",
    "onboarding.enterYourName": "Пожалуйста, введите ваше имя",
    "onboarding.yourNamePlaceholder": "Ваше имя",
    "onboarding.whatToDevelop": "Что вы хотите развивать?",
    "onboarding.chooseFocusArea": "Выберите основную область фокуса",
    "onboarding.webDevelopment": "Веб-разработка",
    "onboarding.mobileApps": "Мобильные приложения",
    "onboarding.dataScience": "Наука о данных",
    "onboarding.aiMl": "ИИ/МО",
    "onboarding.devOps": "DevOps",
    "onboarding.design": "Дизайн",
    "onboarding.marketing": "Маркетинг",
    "onboarding.other": "Другое",
    "onboarding.specifyFocusArea": "Укажите вашу область фокуса",
    "onboarding.incomeGoal": "Какая у вас цель по доходу?",
    "onboarding.annualTargetIncome": "Годовая целевая сумма (USD)",
    "onboarding.perYear": "в год",
    "onboarding.achieveByWhen": "К какому времени вы хотите этого достичь?",
    "onboarding.setTargetDeadline": "Установите целевую дату",
    "onboarding.pickDate": "Выберите дату",
    "onboarding.mainObstacles": "Какие у вас основные препятствия?",
    "onboarding.selectAllThatApply": "Выберите все подходящие",
    "onboarding.timeManagement": "Управление временем",
    "onboarding.technicalSkills": "Технические навыки",
    "onboarding.motivation": "Мотивация",
    "onboarding.resources": "Ресурсы",
    "onboarding.network": "Сеть контактов",
    "onboarding.experience": "Опыт",
    "onboarding.confidence": "Уверенность",
    "onboarding.focus": "Фокус",
    "onboarding.continue": "Продолжить",
    "onboarding.createRoadmap": "Создать мой план",
    "onboarding.buildingRoadmap": "Создаем ваш план...",
    "onboarding.analyzingGoals": "Анализируем цели",
    "onboarding.creatingMilestones": "Создаем этапы",
    "onboarding.buildingTimeline": "Строим временную линию",
    "onboarding.yourRoadmap": "Ваш персональный план",
    "onboarding.yourPath": "Вот ваш путь к достижению целей в области",
    "onboarding.foundationBuildingTitle": "Построение фундамента",
    "onboarding.foundationBuildingDescription": "Освойте основы и настройте среду разработки",
    "onboarding.skillDevelopmentTitle": "Развитие навыков",
    "onboarding.skillDevelopmentDescription": "Развивайте ключевые компетенции через практические проекты",
    "onboarding.portfolioCreationTitle": "Создание портфолио",
    "onboarding.portfolioCreationDescription": "Создайте впечатляющие проекты для демонстрации ваших способностей",
    "onboarding.networkApplyTitle": "Сеть и трудоустройство",
    "onboarding.networkApplyDescription": "Налаживайте связи с профессионалами и начинайте подавать заявки",
    "onboarding.incomeOptimizationTitle": "Оптимизация дохода",
    "onboarding.incomeOptimizationDescription": "Масштабируйте доход через продвинутые стратегии",
    "onboarding.weeks": "недели",
    "onboarding.ongoing": "Постоянно",
    "onboarding.goToGoals": "Перейти к моим целям",

    // Dashboard
    "dashboard.goodMorning": "Доброе утро",
    "dashboard.goodAfternoon": "Добрый день",
    "dashboard.goodEvening": "Добрый вечер",
    "dashboard.readyProgress": "Готовы добиться прогресса в ваших целях сегодня?",
    "dashboard.completedGoals": "Выполненные цели",
    "dashboard.thisMonth": "В этом месяце",
    "dashboard.activeSteps": "Активные шаги",
    "dashboard.inProgress": "В процессе",
    "dashboard.streak": "Серия",
    "dashboard.daysActive": "Дней активности",
    "dashboard.weeklyCheckin": "Напоминание о еженедельной проверке",
    "dashboard.timeForReview": "Время для еженедельного обзора прогресса. Давайте посмотрим, как у вас дела!",
    "dashboard.details": "Подробности",
    "dashboard.myGoals": "Мои цели",
    "dashboard.trackObjectives": "Отслеживайте и управляйте своими целями",
    "dashboard.aiCoach": "AI Коуч",
    "dashboard.personalizedGuidance": "Получите персональные рекомендации",
    "dashboard.library": "Библиотека",
    "dashboard.learningResources": "Доступ к обучающим ресурсам",
    "dashboard.recentActivity": "Недавняя активность",
    "dashboard.latestProgress": "Ваш последний прогресс и достижения",
    "dashboard.completed": "Выполнено",
    "dashboard.started": "Начато",
    "dashboard.chatSession": "Сессия с AI Коучем",
    "dashboard.watched": "Просмотрено",
    "dashboard.hoursAgo": "часов назад",
    "dashboard.dayAgo": "день назад",
    "dashboard.daysAgo": "дня назад",
    "dashboard.currentFocus": "Текущий фокус",
    "dashboard.activeGoalProgress": "Прогресс вашей активной цели",
    "dashboard.masterReact": "Освоить React разработку",
    "dashboard.complete": "завершено",
    "dashboard.due": "Срок:",
    "dashboard.nextSteps": "Следующие шаги:",
    "dashboard.completeHooks": "Завершить урок по React Hooks",
    "dashboard.buildTodo": "Создать проект todo приложения",
    "dashboard.learnState": "Изучить управление состоянием",

    // Goals
    "goals.myGoals": "Мои цели",
    "goals.trackProgress": "Отслеживайте свой прогресс и достигайте целей",
    "goals.newGoal": "Новая цель",
    "goals.createNew": "Создать новую цель",
    "goals.setObjective": "Установите новую цель для работы",
    "goals.goalTitle": "Название цели",
    "goals.titlePlaceholder": "например, Изучить программирование на Python",
    "goals.category": "Категория",
    "goals.selectCategory": "Выберите категорию",
    "goals.webDev": "Веб-разработка",
    "goals.mobile": "Мобильная разработка",
    "goals.dataScience": "Наука о данных",
    "goals.business": "Бизнес",
    "goals.description": "Описание",
    "goals.descriptionPlaceholder": "Опишите вашу цель...",
    "goals.deadline": "Крайний срок",
    "goals.cancel": "Отмена",
    "goals.createGoal": "Создать цель",
    "goals.active": "Активная",
    "goals.completed": "Завершена",
    "goals.paused": "Приостановлена",
    "goals.progress": "Прогресс",
    "goals.steps": "шагов",
    "goals.selectGoal": "Выберите цель",
    "goals.clickToView": "Нажмите на цель для просмотра деталей и управления шагами",
    "goals.goalDetails": "Детали цели",
    "goals.status": "Статус",
    "goals.stepsChecklist": "Чек-лист шагов",
    "goals.overdue": "Просрочено",

    // Chat
    "chat.aiCoachChat": "Чат с AI Коучем",
    "chat.coach": "Коуч",
    "chat.mentor": "Ментор",
    "chat.strategist": "Стратег",
    "chat.greeting":
      "Привет! Я ваш AI Коуч. Я здесь, чтобы помочь вам достичь ваших целей и преодолеть трудности. Над чем бы вы хотели поработать сегодня?",
    "chat.askAnything": "Спросите вашего AI коуча о чем угодно...",
    "chat.pinnedGoals": "Закрепленные цели",
    "chat.aiInsights": "AI Инсайты",
    "chat.performBest": "Вы лучше всего работаете в утренние часы",
    "chat.breakingTasks": "Разбиение задач на 25-минутные блоки увеличивает процент завершения",
    "chat.visualLearners": "Визуальные ученики получают пользу от объяснений на основе диаграмм",
    "chat.quickActions": "Быстрые действия",
    "chat.reviewProgress": "Просмотреть мой прогресс",
    "chat.setMilestone": "Установить новый этап",
    "chat.motivationBoost": "Получить заряд мотивации",

    // Library
    "library.contentLibrary": "Библиотека контента",
    "library.exploreCurated": "Изучите кураторские обучающие ресурсы",
    "library.searchContent": "Поиск контента...",
    "library.allCategories": "Все категории",
    "library.sortBy": "Сортировать по",
    "library.video": "Видео",
    "library.article": "Статья",
    "library.watch": "Смотреть",
    "library.read": "Читать",
    "library.videoPlayer": "Видеоплеер",
    "library.articleContent": "Содержание статьи",
    "library.notes": "Заметки",
    "library.noContent": "Контент не найден",
    "library.adjustCriteria": "Попробуйте изменить критерии поиска или фильтра",

    // Analytics
    "analytics.dashboardTitle": "Панель аналитики",
    "analytics.dashboardDescription": "Отслеживайте свой прогресс и показатели производительности",
    "analytics.totalSessions": "Всего сессий",
    "analytics.goalsCompleted": "Целей выполнено",
    "analytics.chatMessages": "Сообщений в чате",
    "analytics.avgSessionTime": "Среднее время сессии",
    "analytics.weeklyRetentionRate": "Еженедельное удержание",
    "analytics.userEngagementOverTime": "Вовлеченность пользователей",
    "analytics.goalsByCategory": "Цели по категориям",
    "analytics.completedGoalsDistribution": "Распределение выполненных целей",
    "analytics.monthlyChatTime": "Ежемесячное время в чате",
    "analytics.timeSpentInCoachingSessions": "Время, проведенное в коучинговых сессиях",
    "analytics.performanceMetrics": "Показатели производительности",
    "analytics.keyIndicators": "Ключевые показатели эффективности",
    "analytics.goalCompletionRate": "Процент выполнения целей",
    "analytics.sessionConsistency": "Постоянство сессий",
    "analytics.learningProgress": "Прогресс в обучении",
    "analytics.engagementScore": "Оценка вовлеченности",
    "analytics.recentSessions": "Недавние сессии",
    "analytics.detailedSessionAnalytics": "Детальная аналитика сессий",
    "analytics.date": "Дата",
    "analytics.duration": "Длительность",
    "analytics.goalsWorked": "Целей в работе",
    "analytics.messages": "Сообщений",
    "analytics.completion": "Завершение",

    // Profile
    "profile.manageProfile": "Управляйте информацией вашего профиля",
    "profile.personalInfo": "Личная информация",
    "profile.updateDetails": "Обновите свои личные данные и предпочтения",
    "profile.name": "Имя",

    // Navigation
    "nav.dashboard": "Панель",
    "nav.goals": "Цели",
    "nav.chat": "Чат",
    "nav.library": "Библиотека",
    "nav.analytics": "Аналитика",
    "nav.home": "Главная",
    "nav.profile": "Профиль",
    "nav.settings": "Настройки",
    "nav.logout": "Выйти",
    "nav.toggleTheme": "Переключить тему",
    "nav.light": "Светлая",
    "nav.dark": "Темная",
    "nav.system": "Системная",

    // Common
    "common.loading": "Загрузка...",
    "common.save": "Сохранить",
    "common.edit": "Редактировать",
    "common.delete": "Удалить",
    "common.close": "Закрыть",
    "common.back": "Назад",
    "common.next": "Далее",
    "common.previous": "Предыдущий",
    "common.search": "Поиск",
    "common.filter": "Фильтр",
    "common.all": "Все",
    "common.none": "Нет",
    "common.yes": "Да",
    "common.no": "Нет",
    "common.ok": "ОК",
    "common.error": "Ошибка",
    "common.success": "Успех",
    "common.warning": "Предупреждение",
    "common.info": "Информация",
  },
  en: {
    // Auth
    "auth.aiCoach": "AI Coach",
    "auth.personalCompanion": "Your personal development companion",
    "auth.password": "Password",
    "auth.login": "Login",
    "auth.register": "Register",
    "auth.noAccount": "Don't have an account?",
    "auth.alreadyAccount": "Already have an account?",
    "auth.registrationError": "Registration Error",
    "auth.registrationFailedGeneric": "Failed to register. Please try again.",
    "auth.registrationSuccess": "Registration Successful",
    "auth.checkEmailForConfirmation": "Please check your email for confirmation.",
    "auth.accessDenied": "Access Denied",
    "auth.linkExpired": "The link has expired or is invalid.",
    "auth.contactTelegram": "Contact Telegram Support",

    // Onboarding
    "onboarding.step": "Step",
    "onboarding.of": "of",
    "onboarding.personalizeExperience": "Let's personalize your coaching experience",
    "onboarding.whatsYourName": "What's your name?",
    "onboarding.enterYourName": "Please enter your name",
    "onboarding.yourNamePlaceholder": "Your Name",
    "onboarding.whatToDevelop": "What do you want to develop?",
    "onboarding.chooseFocusArea": "Choose your primary focus area",
    "onboarding.webDevelopment": "Web Development",
    "onboarding.mobileApps": "Mobile Apps",
    "onboarding.dataScience": "Data Science",
    "onboarding.aiMl": "AI/ML",
    "onboarding.devOps": "DevOps",
    "onboarding.design": "Design",
    "onboarding.marketing": "Marketing",
    "onboarding.other": "Other",
    "onboarding.specifyFocusArea": "Specify your focus area",
    "onboarding.incomeGoal": "What's your income goal?",
    "onboarding.annualTargetIncome": "Annual target income (USD)",
    "onboarding.perYear": "per year",
    "onboarding.achieveByWhen": "By when do you want to achieve this?",
    "onboarding.setTargetDeadline": "Set your target deadline",
    "onboarding.pickDate": "Pick a date",
    "onboarding.mainObstacles": "What are your main obstacles?",
    "onboarding.selectAllThatApply": "Select all that apply",
    "onboarding.timeManagement": "Time Management",
    "onboarding.technicalSkills": "Technical Skills",
    "onboarding.motivation": "Motivation",
    "onboarding.resources": "Resources",
    "onboarding.network": "Network",
    "onboarding.experience": "Experience",
    "onboarding.confidence": "Confidence",
    "onboarding.focus": "Focus",
    "onboarding.continue": "Continue",
    "onboarding.createRoadmap": "Create My Roadmap",
    "onboarding.buildingRoadmap": "Building your roadmap...",
    "onboarding.analyzingGoals": "Analyzing goals",
    "onboarding.creatingMilestones": "Creating milestones",
    "onboarding.buildingTimeline": "Building timeline",
    "onboarding.yourRoadmap": "Your Personalized Roadmap",
    "onboarding.yourPath": "Here's your path to achieving your",
    "onboarding.foundationBuildingTitle": "Foundation Building",
    "onboarding.foundationBuildingDescription": "Master the fundamentals and set up your development environment",
    "onboarding.skillDevelopmentTitle": "Skill Development",
    "onboarding.skillDevelopmentDescription": "Build core competencies through hands-on projects",
    "onboarding.portfolioCreationTitle": "Portfolio Creation",
    "onboarding.portfolioCreationDescription": "Create impressive projects to showcase your abilities",
    "onboarding.networkApplyTitle": "Network & Apply",
    "onboarding.networkApplyDescription": "Connect with professionals and start applying for opportunities",
    "onboarding.incomeOptimizationTitle": "Income Optimization",
    "onboarding.incomeOptimizationDescription": "Scale your income through advanced strategies",
    "onboarding.weeks": "weeks",
    "onboarding.ongoing": "Ongoing",
    "onboarding.goToGoals": "Go to my goals",

    // Dashboard
    "dashboard.goodMorning": "Good morning",
    "dashboard.goodAfternoon": "Good afternoon",
    "dashboard.goodEvening": "Good evening",
    "dashboard.readyProgress": "Ready to make progress on your goals today?",
    "dashboard.completedGoals": "Completed Goals",
    "dashboard.thisMonth": "This month",
    "dashboard.activeSteps": "Active Steps",
    "dashboard.inProgress": "In progress",
    "dashboard.streak": "Streak",
    "dashboard.daysActive": "Days active",
    "dashboard.weeklyCheckin": "Weekly Check-in Reminder",
    "dashboard.timeForReview": "It's time for your weekly progress review. Let's see how you're doing!",
    "dashboard.details": "Details",
    "dashboard.myGoals": "My Goals",
    "dashboard.trackObjectives": "Track and manage your objectives",
    "dashboard.aiCoach": "AI Coach",
    "dashboard.personalizedGuidance": "Get personalized guidance",
    "dashboard.library": "Library",
    "dashboard.learningResources": "Access learning resources",
    "dashboard.recentActivity": "Recent Activity",
    "dashboard.latestProgress": "Your latest progress and achievements",
    "dashboard.completed": "Completed",
    "dashboard.started": "Started",
    "dashboard.chatSession": "Chat session with AI Coach",
    "dashboard.watched": "Watched",
    "dashboard.hoursAgo": "hours ago",
    "dashboard.dayAgo": "day ago",
    "dashboard.daysAgo": "days ago",
    "dashboard.currentFocus": "Current Focus",
    "dashboard.activeGoalProgress": "Your active goal progress",
    "dashboard.masterReact": "Master React Development",
    "dashboard.complete": "complete",
    "dashboard.due": "Due:",
    "dashboard.nextSteps": "Next Steps:",
    "dashboard.completeHooks": "Complete React Hooks tutorial",
    "dashboard.buildTodo": "Build a todo app project",
    "dashboard.learnState": "Learn state management",

    // Goals
    "goals.myGoals": "My Goals",
    "goals.trackProgress": "Track your progress and achieve your objectives",
    "goals.newGoal": "New Goal",
    "goals.createNew": "Create New Goal",
    "goals.setObjective": "Set a new objective to work towards",
    "goals.goalTitle": "Goal Title",
    "goals.titlePlaceholder": "e.g., Learn Python Programming",
    "goals.category": "Category",
    "goals.selectCategory": "Select category",
    "goals.webDev": "Web Development",
    "goals.mobile": "Mobile Development",
    "goals.dataScience": "Data Science",
    "goals.business": "Business",
    "goals.description": "Description",
    "goals.descriptionPlaceholder": "Describe your goal...",
    "goals.deadline": "Deadline",
    "goals.cancel": "Cancel",
    "goals.createGoal": "Create Goal",
    "goals.active": "Active",
    "goals.completed": "Completed",
    "goals.paused": "Paused",
    "goals.progress": "Progress",
    "goals.steps": "steps",
    "goals.selectGoal": "Select a Goal",
    "goals.clickToView": "Click on a goal to view details and manage steps",
    "goals.goalDetails": "Goal Details",
    "goals.status": "Status",
    "goals.stepsChecklist": "Steps Checklist",
    "goals.overdue": "Overdue",

    // Chat
    "chat.aiCoachChat": "AI Coach Chat",
    "chat.coach": "Coach",
    "chat.mentor": "Mentor",
    "chat.strategist": "Strategist",
    "chat.greeting":
      "Hello! I'm your AI Coach. I'm here to help you achieve your goals and overcome challenges. What would you like to work on today?",
    "chat.askAnything": "Ask your AI coach anything...",
    "chat.pinnedGoals": "Pinned Goals",
    "chat.aiInsights": "AI Insights",
    "chat.performBest": "You perform best in the morning hours",
    "chat.breakingTasks": "Breaking tasks into 25-min chunks increases completion rate",
    "chat.visualLearners": "Visual learners benefit from diagram-based explanations",
    "chat.quickActions": "Quick Actions",
    "chat.reviewProgress": "Review my progress",
    "chat.setMilestone": "Set new milestone",
    "chat.motivationBoost": "Get motivation boost",

    // Library
    "library.contentLibrary": "Content Library",
    "library.exploreCurated": "Explore curated learning resources",
    "library.searchContent": "Search content...",
    "library.allCategories": "All Categories",
    "library.sortBy": "Sort by",
    "library.video": "Video",
    "library.article": "Article",
    "library.watch": "Watch",
    "library.read": "Read",
    "library.videoPlayer": "Video Player",
    "library.articleContent": "Article Content",
    "library.notes": "Notes",
    "library.noContent": "No content found",
    "library.adjustCriteria": "Try adjusting your search or filter criteria",

    // Analytics
    "analytics.dashboardTitle": "Analytics Dashboard",
    "analytics.dashboardDescription": "Track your progress and performance metrics",
    "analytics.totalSessions": "Total Sessions",
    "analytics.goalsCompleted": "Goals Completed",
    "analytics.chatMessages": "Chat Messages",
    "analytics.avgSessionTime": "Avg. Session Time",
    "analytics.weeklyRetentionRate": "Weekly Retention Rate",
    "analytics.userEngagementOverTime": "User engagement over time",
    "analytics.goalsByCategory": "Goals by Category",
    "analytics.completedGoalsDistribution": "Completed goals distribution",
    "analytics.monthlyChatTime": "Monthly Chat Time",
    "analytics.timeSpentInCoachingSessions": "Time spent in coaching sessions",
    "analytics.performanceMetrics": "Performance Metrics",
    "analytics.keyIndicators": "Key performance indicators",
    "analytics.goalCompletionRate": "Goal Completion Rate",
    "analytics.sessionConsistency": "Session Consistency",
    "analytics.learningProgress": "Learning Progress",
    "analytics.engagementScore": "Engagement Score",
    "analytics.recentSessions": "Recent Sessions",
    "analytics.detailedSessionAnalytics": "Detailed session analytics",
    "analytics.date": "Date",
    "analytics.duration": "Duration",
    "analytics.goalsWorked": "Goals Worked",
    "analytics.messages": "Messages",
    "analytics.completion": "Completion",

    // Profile
    "profile.manageProfile": "Manage your profile information",
    "profile.personalInfo": "Personal Information",
    "profile.updateDetails": "Update your personal details and preferences",
    "profile.name": "Name",

    // Navigation
    "nav.dashboard": "Dashboard",
    "nav.goals": "Goals",
    "nav.chat": "Chat",
    "nav.library": "Library",
    "nav.analytics": "Analytics",
    "nav.home": "Home",
    "nav.profile": "Profile",
    "nav.settings": "Settings",
    "nav.logout": "Log out",
    "nav.toggleTheme": "Toggle theme",
    "nav.light": "Light",
    "nav.dark": "Dark",
    "nav.system": "System",

    // Common
    "common.loading": "Loading...",
    "common.save": "Save",
    "common.edit": "Edit",
    "common.delete": "Delete",
    "common.close": "Close",
    "common.back": "Back",
    "common.next": "Next",
    "common.previous": "Previous",
    "common.search": "Search",
    "common.filter": "Filter",
    "common.all": "All",
    "common.none": "None",
    "common.yes": "Yes",
    "common.no": "No",
    "common.ok": "OK",
    "common.error": "Error",
    "common.success": "Success",
    "common.warning": "Warning",
    "common.info": "Info",
  },
}
